name: Generar Keystore (temporal)

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Generar keystore
        run: |
          keytool -genkeypair -v \
            -keystore release.keystore.jks \
            -alias ecopos \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "PanconQueso74" \
            -keypass "PanconQueso74" \
            -dname "CN=EcoPos, OU=EcoPos, O=EcoPos, L=Ciudad, S=Estado, C=PE"

      - name: Subir keystore como artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: release.keystore.jks
